### ISSUE TITLE
PDF Export appears to be resulting in compressed images in the final doc (quality reduction)

### ISSUE THREAD

**Issue by nhmkdev** [nhmkdev/pdfconstruct#3]
There is hopefully a setting with PDFSharp to avoid this!

**Comment by jmb496** [comment]
Just checking on on this.  It seems to work great except for the compressed images.

**Comment by nhmkdev** [comment]
Thanks for reminding me! I have been distracted by other things.

It is strange that CardMaker does not have this issue. I'll have to duplicate the CardMaker code line-for-line and see if that helps. I did some research and testing but nothing seemed to remove the compression. I hope to get a chance to investigate in the next few days.

**Comment by jmb496** [comment]
Thanks so much!

**Comment by nhmkdev** [comment]
I think this is resolved in the 0.0.0.3 release (at least it was for me!)

**Comment by jmb496** [comment]
Worked great for me.  Thank you.
