### ISSUE TITLE
Card Backs Come First

### ISSUE THREAD

**Issue by jmb496** [nhmkdev/pdfconstruct#5]
I made an error in describing the format to you.  Apparently the card backs come before the card fronts, so page 1 is the card 1 back, page 2 is the card 1 front, and so on.  Obviously the app is still functional, but the card front/back labels are reversed according to the DTC format.

Thanks.

**Comment by jmb496** [comment]
Although the big downside I see as I update my pdf is that adding multiple images only works for card fronts...

**Comment by nhmkdev** [comment]
I think the easiest change to make would be an option (checkbox) to indicate "Add Back First on Export."  What do you think?

**Comment by jmb496** [comment]
That would certainly work

**Comment by nhmkdev** [comment]
This should be functional with v0.0.0.4. (new check box)
