### ISSUE TITLE
Close Button 

### ISSUE THREAD

**Issue by jmb496** [nhmkdev/pdfconstruct#6]
Minor issue, but noticed the close button doesn't do anything.

**Comment by nhmkdev** [comment]
If you mean the Close menu option from the file menu I'll have that fixed in the next version. If it's the main X button I'm not sure what might be causing that...

**Comment by jmb496** [comment]
Yes - close from the file menu is what I'm referring to.

**Comment by nhmkdev** [comment]
This should be functional with v0.0.0.4.
